### PR TITLE
Feat/get location

### PR DESCRIPTION
**Pull request by terencetmac**
Updated SearchView > Filters UI

Added feature to allow users to get current location

@wdku5791 can you help to merge please

### CODE REVIEW

**Comment by wdku5791** [comment]
There are some inconsistencies in how you use { deconstruction } vs {deconstruction} in some of your code. i don't know if you did that on purpose.

**Comment by terencetmac** [comment]
hm, do you have specific examples that you can point out?

**Comment by wdku5791** [comment]
searchbar.jsx line 79 onClick={this.getCurrentPosition} >

**Comment by terencetmac** [comment]
Ok I didn't touch FilterListEntry on this commit, but will be doing that in the next PR.

Also, just ignore the style ones for now, those are just temporary until there's enough to put it into a className or something.

**Pull request merged**
